# https://taskfile.org

version: '2'
expansions: 3

env:

vars:
  GREETING: Hello, World!

  GO: go
  GOFLAGS: -i -v
  EXTRA_GOFLAGS:
  GO111MODULE: off
  LDFLAGS: '-X \"main.Version={{.GITEA_VERSION}}\" -X \"main.Tags={{with .TAGS}}{{.TAGS}}{{end}}\"'
  GOFMT: gofmt -s

  DIST: dist
  IMPORT: code.gitea.io/gitea
  EXECUTABLE: |
    {{- if eq OS "windows" -}}
      gitea.exe
    {{- else -}}
      gitea
    {{- end -}}

  SED_INPLACE: |
    {{- if eq OS "darwin" -}}
      sed -i ''
    {{- else -}}
      sed -i
    {{- end -}}

  BINDATA: modules/{options,public,templates}/bindata.go
  GOFILES:
    sh: find . -name "*.go" -type f ! -path "./vendor/*" ! -path "*/bindata.go"
  VERSION: |
    {{- with .DRONE_TAG -}}
      {{trimAll "v" .DRONE_TAG}}
    {{- else -}}
      {{- with .DRONE_BRANCH -}}
        {{trimPrefix "release/v" .DRONE_BRANCH}}
      {{- else -}}
        master
      {{- end -}}
    {{- end -}}

  GITEA_TAG:
    sh: git describe --tags --always | sed 's/-/+/' | sed 's/^v//'
  GITEA_VERSION: |
    {{- with .DRONE_TAG -}}
      {{.VERSION}}
    {{- else -}}
      {{.GITEA_TAG}}
    {{- end -}}

  PACKAGES:
    sh: {{.GO | default "go"}} list ./... | grep -v code.gitea.io/gitea/integrations

  SOURCES:
    sh: find . -name "*.go" -type f


tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  executable:
    cmds:
      - $GO build $GOFLAGS $EXTRA_GOFLAGS -tags '$TAGS' -ldflags '-s -w $LDFLAGS' -o {{.EXECUTABLE}}
    sources:
      - {{.SOURCES}}

  show-vars:
    cmds:
      - echo "OS={{OS}}"
      - echo "EXECUTABLE={{.EXECUTABLE}}"
      - echo "SED_INPLACE={{.SED_INPLACE}}"
      - echo "BINDATA={{.BINDATA}}"
        #      - echo "GOFILES={{.GOFILES}}"
      - echo "GOFLAGS=$GOFLAGS"
      - echo "EXTRA_GOFLAGS=$EXTRA_GOFLAGS"
      - echo "VERSION={{.VERSION}}"
      - echo "GITEA_VERSION={{.GITEA_VERSION}}"
      - echo "LDFLAGS=$LDFLAGS"
      - echo "PACKAGES={{.PACKAGES}}"
    silent: true


